# Generated by Django 5.1.7 on 2025-04-07 19:42

import datetime
import django.db.models.deletion
import visitantes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[visitantes.models.validar_solo_letras])),
                ('apellido', models.CharField(max_length=100, validators=[visitantes.models.validar_solo_letras])),
                ('documento', models.CharField(max_length=20, unique=True, validators=[visitantes.models.validar_documento])),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[visitantes.models.validar_telefono])),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('edad', models.IntegerField()),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro'), (4, 'Prefiero no decirlo')])),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.BooleanField(default=False)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('rif_empresa', models.CharField(blank=True, max_length=20, null=True, validators=[visitantes.models.validar_rif])),
                ('es_extranjero', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='Pendiente', max_length=20)),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitantes.visitante')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('status', models.CharField(default='Agendado', max_length=20)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitantes.visitante')),
            ],
        ),
    ]
