# Generated by Django 5.1.7 on 2025-04-02 00:53

import django.db.models.deletion
import visitantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0002_empresa_pais_sexo_statuscita_statusvisita_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-fecha_visita'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.AlterModelOptions(
            name='visitahora',
            options={'ordering': ['hora_visita'], 'verbose_name': 'Hora de Visita', 'verbose_name_plural': 'Horas de Visita'},
        ),
        migrations.AlterModelOptions(
            name='visitante',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='visitante',
            field=models.OneToOneField(blank=True, help_text='Visitante asociado a esta empresa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_relacionada', to='visitantes.visitante'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rif',
            field=models.CharField(help_text='RIF de la empresa (solo números)', max_length=20, unique=True, validators=[visitantes.models.validar_rif]),
        ),
    ]
